### PR TITLE
Fixes macos compatibility

### PR DESCRIPTION
**Pull request by mariusrugan**
Makefile - docker-build - adds linux compatible flags
docker-compose - entrypoint / cmd removed; moved to dockerfile; added bash script to check via nc postgres is up;
added .gitignore

---
This change is [Reviewable](https://reviewable.io/reviews/dimonomid/geekmarks/10)

### CODE REVIEW

**Comment by dimonomid** [comment]
Thanks, I'll review in the evening.

**Comment by dimonomid** [comment]
See my inline comments below. Please respond at Reviewable, so all discussion flows are preserved.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[.gitignore, line 1 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbcxVCwAklceYquQMc:-KdbcxVCwAklceYquQMd:b3ri8hc) ([raw file](https://github.com/dimonomid/geekmarks/blob/708a701265d57dee114df57ecea5c422e8af6dff/.gitignore#L1)):*
> ```
> #
> ```

Honestly I'm not a fan of adding all these files to the project's gitignore; e.g. for linux users these are completely irrelevant. Since they are generally common for mac, wouldn't it be better if Mac uses have them in their global gitignore?

Or, if global gitignore is not a very good idea for some reason, then put them in `.git/info/exclude`.

---

*[.gitignore, line 36 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbczjF5Dmgu-x4Jhv-:-KdbczjF5Dmgu-x4Jhv0:b-v5hqo1) ([raw file](https://github.com/dimonomid/geekmarks/blob/708a701265d57dee114df57ecea5c422e8af6dff/.gitignore#L36)):*
> ```
> # Project
> #
> server/geekmarks-server
> ```

Please add a newline at the end of file

---

*[server/Dockerfile, line 15 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbfHwf5CaFjgq-0C8O:-KdbfHwgYFu2NQJ6MXJV:bpd4ver) ([raw file](https://github.com/dimonomid/geekmarks/blob/708a701265d57dee114df57ecea5c422e8af6dff/server/Dockerfile#L15)):*
> ```Dockerfile
> RUN chmod +x /geekmarks-server
> 
> CMD ["/start.sh", "geekmarks-dev-postgres", "/geekmarks-server", "--logtostderr --v=5 --geekmarks.port=4000 --geekmarks.postgres.url=postgres://geekmarks:geekmarks@postgres:5432/geekmarks?sslmode=disable --google_oauth_creds_file=/data/google_oauth_creds.yaml"]
> ```

It's better to keep docker images as neutral as possible, just like the binaries they wrap: it's the caller who cares about all these flags. Let's not put those defaults here, and put them back to `docker-compose.yml`.

---

*[server/Dockerfile, line 17 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbdILFU5gd1M9KvWLK:-KdbdILFU5gd1M9KvWLL:b-v5hqo1) ([raw file](https://github.com/dimonomid/geekmarks/blob/708a701265d57dee114df57ecea5c422e8af6dff/server/Dockerfile#L17)):*
> ```Dockerfile
> CMD ["/start.sh", "geekmarks-dev-postgres", "/geekmarks-server", "--logtostderr --v=5 --geekmarks.port=4000 --geekmarks.postgres.url=postgres://geekmarks:geekmarks@postgres:5432/geekmarks?sslmode=disable --google_oauth_creds_file=/data/google_oauth_creds.yaml"]
> 
> EXPOSE 4000
> ```

Please add a newline at the end of file

---

*[server/Makefile, line 10 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbdKIyR3TLkBw98Zvu:-KdbdKIyR3TLkBw98Zvv:b-524vy) ([raw file](https://github.com/dimonomid/geekmarks/blob/48d600f8638df7afbf55802946e70f64328aa4a8/server/Makefile#L10)):*
> ```Makefile
> docker-build:
> 	go generate dmitryfrank.com/geekmarks/...
> 	go build --race -i dmitryfrank.com/geekmarks/server/cmd/geekmarks-server
> ```

Why did you remove `--race`? I do want race conditions to be caught.

---

*[server/envs/dev/docker-compose.yml, line 9 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbdMyELRQfS7RP6h1i:-KdbdMyELRQfS7RP6h1j:b-8t6uqd) ([raw file](https://github.com/dimonomid/geekmarks/blob/48d600f8638df7afbf55802946e70f64328aa4a8/server/envs/dev/docker-compose.yml#L9)):*
> ```YAML
>     image: library/postgres:9.6
>     volumes:
>       - "/var/tmp/geekmarks_dev/postgresql:/var/lib/postgresql/data"
> ```

Why did you remove `/var`? Stuff in `/tmp` gets removed occasionally (on my Linux Mint, on every reboot), whereas stuff in `/var/tmp` stay.

---

*[server/envs/dev/docker-compose.yml, line 11 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbdP6QDigLPzWboa3v:-KdbdP6QDigLPzWboa3w:bt4ueex) ([raw file](https://github.com/dimonomid/geekmarks/blob/48d600f8638df7afbf55802946e70f64328aa4a8/server/envs/dev/docker-compose.yml#L11)):*
> ```YAML
>       - "/var/tmp/geekmarks_dev/postgresql:/var/lib/postgresql/data"
>     #ports:
>       #- "5432:5432"
> ```

Why exposing the port 5432 to the host machine? Afaik it's not necessary for the adjacent container (geekmarks) to access it.

---

*[server/envs/dev/docker-compose.yml, line 27 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbdSG6BfgqaJ_myGHd:-KdbdSG6BfgqaJ_myGHe:blok9ro) ([raw file](https://github.com/dimonomid/geekmarks/blob/48d600f8638df7afbf55802946e70f64328aa4a8/server/envs/dev/docker-compose.yml#L27)):*
> ```YAML
>       - "4000:4000"
>     volumes:
>       - "/var/tmp/geekmarks_dev/main:/data"
> ```

Same thing about `/var/tmp`.

---

*[server/envs/dev/docker-compose.yml, line 33 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-Kdbda3S7I_Gvy8TxPK8:-Kdbda3S7I_Gvy8TxPK9:b-eduw9q) ([raw file](https://github.com/dimonomid/geekmarks/blob/48d600f8638df7afbf55802946e70f64328aa4a8/server/envs/dev/docker-compose.yml#L33)):*
> ```YAML
>       --geekmarks.postgres.url=postgres://geekmarks:geekmarks@postgres:5432/geekmarks?sslmode=disable
>       --google_oauth_creds_file=/data/google_oauth_creds.yaml
>     restart: never
> ```

Why did you remove `restart: never`? When geekmarks crashes for any reason, I don't really want it to crashloop and pollute logs; I want it to crash just once and exit.

---

*[server/envs/test/docker-compose.yml, line 9 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-KdbdwlaY2Oe5qxwGC4Z:-KdbdwlaY2Oe5qxwGC4_:bc5m7lm) ([raw file](https://github.com/dimonomid/geekmarks/blob/48d600f8638df7afbf55802946e70f64328aa4a8/server/envs/test/docker-compose.yml#L9)):*
> ```YAML
>     image: library/postgres:9.6
>     volumes:
>       - "/var/tmp/geekmarks_test/postgresql:/var/lib/postgresql/data"
> ```

Same thing about `/var/tmp`

---

*[server/scripts/start.sh, line 1 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-Kdbe-wfwbwAT6oBSR1x:-Kdbe-wg0WsuLZ-jyAU5:bbxlm0r) ([raw file](https://github.com/dimonomid/geekmarks/blob/708a701265d57dee114df57ecea5c422e8af6dff/server/scripts/start.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

I don't really understand why this magic with `start.sh` and `nc` is needed. Could you please add detailed comment about why and how?

---

*[server/scripts/start.sh, line 18 at r1](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-Kdbe4Tl60bHFy8zPS-F:-Kdbe4Tl60bHFy8zPS-G:b-v5hqo1) ([raw file](https://github.com/dimonomid/geekmarks/blob/708a701265d57dee114df57ecea5c422e8af6dff/server/scripts/start.sh#L18)):*
> ```Shell
> 
> >&2 echo "Postgres is up - executing command"
> exec $CMD
> ```

Please add a newline at the end of file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dimonomid/geekmarks/10#-:-KdbfTMDdPqSscaH5mTN:bsg9xts)*

**Comment by mariusrugan** [comment]
hi,
thanks for looking into it, although is poorly documented 
(for example what i experienced is postgres container goes vacuum-ing and geekmarks binary in the other container exits because of the connection unavailable - that's why the port probing solution) 
agree to your points and i'll look into it tomorrow to see where it can improve and also bounce some ideas back&forth.

**Comment by dimonomid** [comment]
Also, just a suggestion based on my experience with constant PR-review-merge cycle in our company: it's much more convenient if we make a PR from some feature branch, not from master, and the PR almost always consists of just a single focused commit. This way, the review comments can be addressed by amending the commit and force-pushing the feature branch, and eventually the master does not get polluted by lots of half-baked stuff. Just one focused and polished commit gets merged into master.

**Comment by dimonomid** [comment]
Closing this one, hopefully will sort it out separately.

**Pull request closed without merging**
